- op: add
  path: /spec/template/spec/initContainers/0
  value:
    name: secret-init
    command: [ 'argocd', 'admin', 'redis-initial-password' ]
    image: quay.io/argoproj/argocd:2.14.2
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault